
name: 'N1 - Execução Manual'

on:
  workflow_dispatch:

jobs:

  e2e-testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencies
        run: yarn

      - name: Testes e2e
        run: yarn cypress run

