name: 'N1 Manual Execution'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencies
        run: yarn

      - name: Testes e2e
        run: yarn cypress run

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: tests_reports
          path: ./cypress/reports/html

      - name: Notification Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TARGET_BRANCH: ${{ secrets.TARGET_BRANCH }}
        run:
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "Build feita com sucesso! ✅ \nStatus: `${{ job.status }}` \nAutor: @${{ github.actor }}"
          $DISCORD_WEBHOOK_URL
