name: "N2 Scheduled Execution"

on:
  schedule:
    - cron: "10 8 27 10 *"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: E2E Test
        run: yarn cypress run

      - uses: actions/upload-artifact@v4
        with:
          name: tests_reports
          path: ./cypress/reports/html

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TARGET_BRANCH: ${{ secrets.TARGET_BRANCH }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "Scheduled Pipeline! ✅ \nStatus: `${{ job.status }}` \nAuthor: @${{ github.actor }}"}' \
          $DISCORD_WEBHOOK_URL
